### ISSUE TITLE
Exception when send message to using library - The DirectLineChatbot must be initialized first. Call start().

### ISSUE THREAD

**Issue by hjain1** [smartnsoft/directline-chatbot-android-sdk#1]
chatbot = new DirectLineChatbot(Constants.AUTH_TOKEN);
        chatbot.setUser("user1");
        chatbot.setDebug(true);
        chatbot.start(new DirectLineChatbot.Callback()
        {
            @Override
            public void onStarted()
            {
                Log.d("CHATBOT", "Started");
            }

            @Override
            public void onMessageReceived(@NotNull String message)
            {
                Log.d("CHATBOT", message);
            }
        });

Already added start callback before send.

**Comment by david-fournier-smartnsoft** [comment]
Hello,

You can only send messages once the `onStarted()` callback has been triggered.
We will throw a more meaningful exception though.

Thanks
